/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DumpsRouteImport } from './routes/dumps'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesRepoIdRouteImport } from './routes/repositories.$repoId'
import { Route as RepositoriesRepoIdIndexRouteImport } from './routes/repositories.$repoId.index'
import { Route as RepositoriesRepoIdBranchRouteImport } from './routes/repositories.$repoId.$branch'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DumpsRoute = DumpsRouteImport.update({
  id: '/dumps',
  path: '/dumps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesRepoIdRoute = RepositoriesRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesRepoIdIndexRoute = RepositoriesRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRepoIdRoute,
} as any)
const RepositoriesRepoIdBranchRoute =
  RepositoriesRepoIdBranchRouteImport.update({
    id: '/$branch',
    path: '/$branch',
    getParentRoute: () => RepositoriesRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dumps': typeof DumpsRoute
  '/events': typeof EventsRoute
  '/exports': typeof ExportsRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/': typeof RepositoriesIndexRoute
  '/search': typeof SearchRoute
  '/snapshots': typeof SnapshotsRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRouteWithChildren
  '/repositories/$repoId/$branch': typeof RepositoriesRepoIdBranchRoute
  '/repositories/$repoId/': typeof RepositoriesRepoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dumps': typeof DumpsRoute
  '/events': typeof EventsRoute
  '/exports': typeof ExportsRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/search': typeof SearchRoute
  '/snapshots': typeof SnapshotsRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/repositories/$repoId/$branch': typeof RepositoriesRepoIdBranchRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dumps': typeof DumpsRoute
  '/events': typeof EventsRoute
  '/exports': typeof ExportsRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/': typeof RepositoriesIndexRoute
  '/search': typeof SearchRoute
  '/snapshots': typeof SnapshotsRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRouteWithChildren
  '/repositories/$repoId/$branch': typeof RepositoriesRepoIdBranchRoute
  '/repositories/$repoId/': typeof RepositoriesRepoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dumps'
    | '/events'
    | '/exports'
    | '/repositories'
    | '/repositories/'
    | '/search'
    | '/snapshots'
    | '/system'
    | '/tasks'
    | '/repositories/$repoId'
    | '/repositories/$repoId/$branch'
    | '/repositories/$repoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dumps'
    | '/events'
    | '/exports'
    | '/repositories'
    | '/search'
    | '/snapshots'
    | '/system'
    | '/tasks'
    | '/repositories/$repoId/$branch'
    | '/repositories/$repoId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dumps'
    | '/events'
    | '/exports'
    | '/repositories'
    | '/repositories/'
    | '/search'
    | '/snapshots'
    | '/system'
    | '/tasks'
    | '/repositories/$repoId'
    | '/repositories/$repoId/$branch'
    | '/repositories/$repoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DumpsRoute: typeof DumpsRoute
  EventsRoute: typeof EventsRoute
  ExportsRoute: typeof ExportsRoute
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  SearchRoute: typeof SearchRoute
  SnapshotsRoute: typeof SnapshotsRoute
  SystemRoute: typeof SystemRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dumps': {
      id: '/dumps'
      path: '/dumps'
      fullPath: '/dumps'
      preLoaderRoute: typeof DumpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$repoId': {
      id: '/repositories/$repoId'
      path: '/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof RepositoriesRepoIdRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$repoId/': {
      id: '/repositories/$repoId/'
      path: '/'
      fullPath: '/repositories/$repoId/'
      preLoaderRoute: typeof RepositoriesRepoIdIndexRouteImport
      parentRoute: typeof RepositoriesRepoIdRoute
    }
    '/repositories/$repoId/$branch': {
      id: '/repositories/$repoId/$branch'
      path: '/$branch'
      fullPath: '/repositories/$repoId/$branch'
      preLoaderRoute: typeof RepositoriesRepoIdBranchRouteImport
      parentRoute: typeof RepositoriesRepoIdRoute
    }
  }
}

interface RepositoriesRepoIdRouteChildren {
  RepositoriesRepoIdBranchRoute: typeof RepositoriesRepoIdBranchRoute
  RepositoriesRepoIdIndexRoute: typeof RepositoriesRepoIdIndexRoute
}

const RepositoriesRepoIdRouteChildren: RepositoriesRepoIdRouteChildren = {
  RepositoriesRepoIdBranchRoute: RepositoriesRepoIdBranchRoute,
  RepositoriesRepoIdIndexRoute: RepositoriesRepoIdIndexRoute,
}

const RepositoriesRepoIdRouteWithChildren =
  RepositoriesRepoIdRoute._addFileChildren(RepositoriesRepoIdRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  RepositoriesRepoIdRoute: typeof RepositoriesRepoIdRouteWithChildren
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  RepositoriesRepoIdRoute: RepositoriesRepoIdRouteWithChildren,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DumpsRoute: DumpsRoute,
  EventsRoute: EventsRoute,
  ExportsRoute: ExportsRoute,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  SearchRoute: SearchRoute,
  SnapshotsRoute: SnapshotsRoute,
  SystemRoute: SystemRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
